--- 
- hosts: 172.31.6.58
  become: yes
  tasks:
  - include: myfile.yml
  - name: i want to install  tree
    apt:
      name: tree
      state: present     
  - name: copy index file into node side
    copy: 
      src:  myindexpage
      dest: /var/www/html/index.html
  - name: copy dyno files into nodes
  template:
        src:
        dest: