---
- hosts: all 
  become: yes
  tasks: 
  - name: i want to ping all nodes 
    ping:

  - name: i want to install webserver on ubuntu ansible nodes
    apt: 
       name: apache2
       state: absent
  - name: i want install tree on ubuntu ansible nodes
    apt:
     name: tree
    state: absent